export const ROUTES = {
  home: '/',
  liveOrders: '/live-orders',
  liveOrderDetail: (id: number | string) => `/live-orders/${id}`,
  marketplace: '/marketplace',
  agencies: '/agencies',
  agentPortfolio: (agentId: number | string, itemId: number | string) =>
    `/agents/${agentId}/portfolio/${itemId}`,
  products: '/products',
  designers: '/designers',
  tender: '/tender',
  map: '/map',
  chat: '/chat',
  chatThreads: '/chat/threads',
  chatDirect: (id: number | string) => `/chat/direct/${id}`,
  chatOrder: (id: number | string) => `/chat/${id}`,
  notifications: '/notifications',
  orders: '/orders',
  offers: '/offers',
  offerOpportunity: (orderId: number | string) => `/offers/order/${orderId}`,
  offerDetail: (id: number | string) => `/offers/${id}`,
  newOrder: '/orders/new',
  profile: '/profile', // personal account only (tab)
  profileEdit: '/profile/edit',
  earnings: '/earnings',
  clientDetail: (id: number | string) => `/clients/${id}`,
  settings: '/settings',
} as const
